services:
  dimmcie:
    image: denoland/deno:2.1.4
    user: 1000:1000
    ports:
      - "8000:8000"
    volumes:
      - /server/dimmcie/src:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      - IP=LOCALHOST
      - PORT=25569
      - SERVERSHUTDOWNLIMIT=180000
      - CONTAINERID="fa257758aefe"
      - PATHTOWHITELIST="/home/nawaf/Documents/GitHub/dimmcie/minecraft/data/whitelist.json"
      - RCONPORT=25575
    command: deno run --allow-all --unstable-cron main.ts
  
  proxy:
    image:  ghcr.io/minekube/gate:latest
    container_name: minecraft-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
    - /server/dimmcie/config.yml:/config.yml
