services:
  dimmcie:
    image: dimmcie
    container_name: dimmcie
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/nawaf/Documents/GitHub/dimmcie/minecraft/data/whitelist.json:/whitelist.json
    environment:
      - PORT=25569
      - IP=localhost
      - SERVERSHUTDOWNLIMIT=60000 
      - CONTAINERNAME=minecraft-server
      - PATHTOWHITELIST=/whitelist.json
      - CRON=*/1 * * * *

  proxy:
    image:  ghcr.io/minekube/gate:latest
    container_name: minecraft-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
    - /home/nawaf/Documents/GitHub/dimmcie/config.yml:/config.yml
